[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = [
    "-h",
] }

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["install-llvm-tools", "flip-link"]


[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "liris60-central.hex",
]
dependencies = ["build"]

[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "ihex",
    "liris60-peripheral.hex",
]
dependencies = ["build"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "liris60-central.hex",
    "--output-path",
    "liris60-central.uf2",
    "--family",
    "rp2040",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "liris60-peripheral.hex",
    "--output-path",
    "liris60-peripheral.uf2",
    "--family",
    "rp2040",
]
dependencies = ["objcopy-peripheral"]

[tasks.bin-central]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "binary",
    "liris60-central.bin",
]
dependencies = ["build"]

[tasks.bin-peripheral]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "binary",
    "liris60-peripheral.bin",
]
dependencies = ["build"]

[tasks.bin]
dependencies = ["bin-central", "bin-peripheral"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]
